import axios from "axios";

export const BASE_URL = "https://manhwaclan.com";

export const httpClient = axios.create({
  timeout: 8000,
  maxRedirects: 3,
  headers: {
    "Accept-Encoding": "gzip, deflate, br",
  },
});

export enum SortOptions {
  Alphabetical = "alphabetical",
  Trending = "trending",
  RecentlyAdded = "new",
  RecentlyUpdated = "latest",
  Popular = "popular",
  Rating = "rating",
}

export const sortMap: Record<SortOptions, string> = {
  [SortOptions.Alphabetical]: "alphabet",
  [SortOptions.Trending]: "trending",
  [SortOptions.RecentlyAdded]: "new-manga",
  [SortOptions.RecentlyUpdated]: "latest",
  [SortOptions.Popular]: "views",
  [SortOptions.Rating]: "rating",
};

export enum GenreOptions {
  Action = "action",
  Adaptation = "adaptation",
  Adult = "adult",
  Adventure = "adventure",
  Comedy = "comedy",
  Cooking = "cooking",
  Demon = "demon",
  Drama = "drama",
  Fantasy = "fantasy",
  Harem = "harem",
  Historical = "historical",
  Isekai = "isekai",
  Josei = "josei",
  Magic = "magic",
  Magical = "magical",
  Manga = "manga",
  Manhua = "manhua",
  Manhwa = "manhwa",
  MartialArts = "martial-arts",
  Mature = "mature",
  Mystery = "mystery",
  Reincarnation = "reincarnation",
  Romance = "romance",
  SchoolLife = "school-life",
  Shoujo = "shoujo",
  Shounen = "shounen",
  SliceOfLife = "slice-of-life",
  Smut = "smut",
  Supernatural = "supernatural",
  TimeTravel = "time-travel",
  Vampire = "vampire",
  Villainess = "villainess",
  Webtoon = "webtoon",
}

export const genreMap: Record<GenreOptions, string | string[]> = {
  [GenreOptions.Action]: "action",
  [GenreOptions.Adaptation]: "adaptation",
  [GenreOptions.Adult]: "adult",
  [GenreOptions.Adventure]: "adventure",
  [GenreOptions.Comedy]: "comedy",
  [GenreOptions.Cooking]: "cooking",
  [GenreOptions.Demon]: "demon",
  [GenreOptions.Drama]: "drama",
  [GenreOptions.Fantasy]: "fantasy",
  [GenreOptions.Harem]: "harem",
  [GenreOptions.Historical]: "historical",
  [GenreOptions.Isekai]: "isekai",
  [GenreOptions.Josei]: "josei",
  [GenreOptions.Magic]: "magic",
  [GenreOptions.Magical]: "magical",
  [GenreOptions.Manga]: "manga",
  [GenreOptions.Manhua]: "manhua",
  [GenreOptions.Manhwa]: "manhwa",
  [GenreOptions.MartialArts]: "martial-arts",
  [GenreOptions.Mature]: "mature",
  [GenreOptions.Mystery]: "mystery",
  [GenreOptions.Reincarnation]: "reincarnation",
  [GenreOptions.Romance]: "romance",
  [GenreOptions.SchoolLife]: "school-life",
  [GenreOptions.Shoujo]: "shoujo",
  [GenreOptions.Shounen]: "shounen",
  [GenreOptions.SliceOfLife]: "slice-of-life",
  [GenreOptions.Smut]: "smut",
  [GenreOptions.Supernatural]: "supernatural",
  [GenreOptions.TimeTravel]: "time-travel",
  [GenreOptions.Vampire]: "vampire",
  [GenreOptions.Villainess]: "villainess",
  [GenreOptions.Webtoon]: "webtoons",
};
